version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      steamvote-network:
        ipv4_address: 172.18.0.100

  kafka:
    # build: .
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ec2-3-34-143-176.ap-northeast-2.compute.amazonaws.com
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      steamvote-network:
        ipv4_address: 172.18.0.101

networks:
  steamvote-network: 
    external: true